name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: staging
    strategy:
      matrix:
        node-version: [15.x]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Generate build number
      run: echo "The build number $GITHUB_RUN_NUMBER 🏗"
    - name: Install dependencies
      run: | 
        npm install
    - name: Create .env
      run: |
        touch .env &&
        echo "NODE_ENV=${NODE_ENV}" > .env
        echo "APP_ENV=${APP_ENV}" >> .env
        echo "PORT=${PORT}" >> .env
        echo "JWT_SECRET_KEY=${JWT_SECRET_KEY}" >> .env
      env:
        NODE_ENV: ${{ secrets.NODE_ENV }}
        APP_ENV: ${{ secrets.APP_ENV }}
        PORT: ${{ secrets.PORT }}
        JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
    - name: Build docker 🐳
      run: docker build . -t=wallet-auth-api:ghb-$GITHUB_RUN_NUMBER